export const CARGOS_VALIDOS = [
  'Administrador',
  'Analista Administrativo',
  'Analista Contable',
  'Analista Financiero',
  'Analista de Compras',
  'Analista de Recursos Humanos',
  'Analista de Sistemas',
  'Analista de Seguridad',
  'Asesor Comercial',
  'Asesor Jurídico',
  'Asistente Administrativo',
  'Asistente Contable',
  'Asistente de Gerencia',
  'Auxiliar Administrativo',
  'Auxiliar Contable',
  'Auxiliar de Archivo',
  'Auxiliar de Bodega',
  'Auxiliar de Compras',
  'Auxiliar de Logística',
  'Auxiliar de Sistemas',
  'Cajero',
  'Coordinador Administrativo',
  'Coordinador Comercial',
  'Coordinador de Compras',
  'Coordinador de Logística',
  'Coordinador de Recursos Humanos',
  'Coordinador de Seguridad',
  'Coordinador de Sistemas',
  'Director Administrativo',
  'Director Comercial',
  'Director Financiero',
  'Director de Recursos Humanos',
  'Director de Seguridad',
  'Director de Sistemas',
  'Diseñador Gráfico',
  'Ejecutivo Comercial',
  'Especialista de Recursos Humanos',
  'Especialista en Seguridad',
  'Gerente Administrativo',
  'Gerente Comercial',
  'Gerente Financiero',
  'Gerente de Operaciones',
  'Gerente de Recursos Humanos',
  'Gerente de Seguridad',
  'Gerente General',
  'Ingeniero de Sistemas',
  'Ingeniero de Software',
  'Ingeniero Industrial',
  'Jefe Administrativo',
  'Jefe de Compras',
  'Jefe de Logística',
  'Jefe de Recursos Humanos',
  'Jefe de Seguridad',
  'Jefe de Sistemas',
  'Jefe de Talento Humano',
  'Líder Administrativo',
  'Líder Comercial',
  'Líder de Operaciones',
  'Líder de Seguridad',
  'Líder de Sistemas',
  'Mensajero',
  'Operador',
  'Operador de Seguridad',
  'Profesional Administrativo',
  'Profesional Contable',
  'Profesional Financiero',
  'Profesional de Recursos Humanos',
  'Profesional de Seguridad',
  'Recepcionista',
  'Secretario',
  'Supervisor Administrativo',
  'Supervisor de Operaciones',
  'Supervisor de Seguridad',
  'Técnico Administrativo',
  'Técnico de Mantenimiento',
  'Técnico de Sistemas',
  'Técnico en Seguridad',
  'Vigilante',
  'Proveedor de mercancía',
  'Otro',
] as const;